hlw:
  nacos:
    server-addr: 192.168.124.238:8848
    namespace: public
    group: DEFAULT_GROUP
    username: nacos
    password: nacos
  datasource:
    url: jdbc:mysql://192.168.124.238:23308/hospital_gateway?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.124.238
    port: 6379
    password: ""
    database: 0

spring:
  cloud:
    gateway:
      routes:
        - id: hospital-auth-local
          uri: http://127.0.0.1:19100
          predicates:
            - Path=/auth/**
        - id: hospital-system-local
          uri: http://127.0.0.1:19200
          predicates:
            - Path=/system/**
        - id: hospital-doctor-local
          uri: http://127.0.0.1:19400
          predicates:
            - Path=/doctor/**
        - id: hospital-patient-local
          uri: http://127.0.0.1:19300
          predicates:
            - Path=/patient/**
        - id: hospital-appointment-local
          uri: http://127.0.0.1:19600
          predicates:
            - Path=/appointment/**
        - id: hospital-consult-local
          uri: http://127.0.0.1:19500
          predicates:
            - Path=/consult/**,/ws/consult/**
        - id: hospital-prescription-local
          uri: http://127.0.0.1:19700
          predicates:
            - Path=/prescription/**
        - id: hospital-drug-local
          uri: http://127.0.0.1:19800
          predicates:
            - Path=/drug/**
        - id: hospital-order-local
          uri: http://127.0.0.1:19900
          predicates:
            - Path=/order/**
