hlw:
  nacos:
    server-addr: 192.168.124.238:8848
    namespace: public
    group: DEFAULT_GROUP
    username: nacos
    password: nacos
  datasource:
    url: jdbc:mysql://192.168.124.238:23308/hospital_appointment?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.124.238
    port: 6379
    password: ""
    database: 0
  rabbitmq:
    host: 192.168.124.238
    port: 5672
    username: guest
    password: guest
