hlw:
  nacos:
    server-addr: nacos-prod:8848
    namespace: prod
    group: PROD_GROUP
    username: ${NACOS_USERNAME}
    password: ${NACOS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${SYSTEM_DB_HOST}:${SYSTEM_DB_PORT:5432}/${SYSTEM_DB_NAME:hospital_system}
    username: ${SYSTEM_DB_USERNAME}
    password: ${SYSTEM_DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
