hlw:
  nacos:
    server-addr: 127.0.0.1:8848
    namespace: public
    group: DEFAULT_GROUP
    username: nacos
    password: nacos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hospital_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: hospital123
