hlw:
  nacos:
    server-addr: 127.0.0.1:8848
    namespace: public
    group: DEFAULT_GROUP
    username: nacos
    password: nacos
  datasource:
    url: jdbc:mysql://127.0.0.1:23308/hospital_patient
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    database: 0
